name: "Run Reg Suit"
description: "Run Reg Suit"
inputs:
  package:
    required: true
    description: "Package name"

runs:
  using: "composite"
  steps:
    - name: Build storybook for  ${{ inputs.package }}
      shell: bash
      run: npx --no-install build-storybook -c ./packages/${{ inputs.package }}/.storybook -o packages/${{ inputs.package }}/dist-storybook
    - name: Capture components screenshots for ${{ inputs.package }}
      shell: bash
      run: |
        npx --no-install storycap \
        --serverCmd "http-server ./packages/${{ inputs.package }}/dist-storybook -s -p 9020" \
        --outDir ./packages/${{ inputs.package }}/__screenshots__ \
        http://localhost:9020
    - name: Run visual regression
      shell: bash
      run: |
        "cd ./packages/${{ inputs.package }}"
        "../../../node_modules/.bin/reg-suit run -c ./regconfig.json",
